### ISSUE TITLE
Cant use temperature in a flow

### ISSUE THREAD

**Issue by mettin** [kerkenit/nl.marcovantklooster.icyethermostaat#3]
I would like to use the current temperature in a trigger so i can manage the in house temperature better.

i.e.:

When the temperature is >= 25
And nobody is home
And its daytime
Close curtains

**Comment by kerkenit** [comment]
This is available a long time ago. (Before summer)
It's a drop token.
If you don't have a drop token, you have to remove the e-thermostaat and add it again.
![schermafbeelding 2018-09-03 om 16 50 55](https://user-images.githubusercontent.com/13370203/44993142-cd0f7700-af99-11e8-92ac-effa7484466b.png)
